### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by nsomaru** [stx-technologies/stox-token#3]
Any updates? The repo seems a little unattended.

**Comment by lbeder** [comment]
Not at all. This repo was mostly used to power the token sale and further crypto development will be open to the public soon as well.

**Comment by nsomaru** [comment]
Does that mean that development is not conducted in the open? What's the policy?

Can you provide us with development updates, milestones etc.?

**Comment by lbeder** [comment]
Please join our community, where we provide development updates, milestones, and other news:

Twitter: https://t.me/joinchat/DByWw0Pnq9BAy4FqPv_Lyg
Reddit: https://www.reddit.com/r/STOX/

**Comment by nsomaru** [comment]
Strange to direct developers away from github to twitter and reddit. Just to repeat the question:

> Does that mean that development is not conducted in the open? What's the policy?

**Comment by lbeder** [comment]
At the moment, no, but there is a huge shift to make everything open very (very!) soon. Stay tuned.
